phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - yum install -y unzip curl

      - TERRAFORM_VERSION="1.9.5"

      - curl -fsSL -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip

      - ls -lh terraform.zip

      - unzip -o terraform.zip

      - mv terraform /usr/local/bin/

      - terraform -version
