version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install flask
      - echo "Installing Trivy"
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - mv ./bin/trivy /usr/local/bin/

  pre_build:
    commands:
      - echo "=== SECURITY PHASE STARTING ==="

  build:
    commands:
      - echo "Validating Python code"
      - python3 -m py_compile app.py

      - echo "Running Trivy filesystem scan (enterprise mode)"

      # 1. Show clean readable output
      - trivy fs . --severity HIGH,CRITICAL --format table

      # 2. Fail ONLY on HIGH/CRITICAL vulnerabilities
      - trivy fs . --severity HIGH,CRITICAL --exit-code 1

      # 3. Generate report file for auditing (real DevSecOps feature)
      - trivy fs . --severity HIGH,CRITICAL --format json -o trivy-report.json

artifacts:
  files:
    - app.py
    - terraform/*
    - trivy-report.json
