from flask import Flask
from flask_wtf.csrf import CSRFProtect
import os

app = Flask(__name__)

# =========================
# SECURITY CONFIGURATION
# =========================

SECRET_KEY = os.getenv("FLASK_APP_KEY")

if not SECRET_KEY:
    raise RuntimeError("FLASK_APP_KEY environment variable is required")

app.config.update(
    SECRET_KEY=SECRET_KEY
)

# Enable CSRF protection
csrf = CSRFProtect(app)

# =========================
# ROUTES
# =========================

@app.route("/", methods=["GET"])
def home():
    return {
        "status": "ok",
        "message": "DevSecOps Pipeline Running in AWS!"
    }, 200


# =========================
# LOCAL DEV ONLY
# =========================

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8080, debug=False)
