name: SOC2 DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
        HEAD

        HEAD
          set -euo pipefail

          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.71.2/trivy_0.71.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.55.0_Linux-64bit.deb
         c34b873 (Update DevSecOps pipeline fixes)

          echo "Installing Trivy..."
        628b635 (Add .dockerignore to prevent sensitive data leakage)
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh \
            | sudo sh -s -- -b /usr/local/bin

          trivy version

      - name: Trivy FS Scan
        run: |
          trivy fs \
            --scanners vuln,secret \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            .

      - name: Trivy Config Scan
        run: |
          trivy config \
            --severity HIGH,CRITICAL \
            --exit-code 1 \
            .

  build:
      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          exit-code: 1
          severity: HIGH,CRITICAL

  deploy:
    needs: security_scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::150460248370:role/dev-sec-ops-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
