name: SOC2 DevSecOps Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@0.36.0
        with:
          scan-type: config
          scan-ref: .
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

  deploy:
    needs: security_scan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::150460248370:role/dev-sec-ops-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
