name: DevSecOps OIDC Test

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # REQUIRED for AWS OIDC

jobs:
  aws-auth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::150460248370:role/dev-sec-ops-role
          aws-region: us-east-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity
